apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete-task
  labels:
    app.kubernetes.io/name: delete-task
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: deletetask.devopsinsight.biz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: delete-task
            port: 
              number: 80
